# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'vs2015-win2012r2'

variables:
  solution: 'AgoraPlayerHookPlugin/AgoraPlayerHookPlugin.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  
steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '14.0'
    msbuildArchitecture: 'x86'
   
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'AgoraPlayerHookPlugin/Release/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: AgoraPlayerHookPlugin.zip
    replaceExistingArchive: true

- publish: AgoraPlayerHookPlugin.zip
  artifact: HookPlayerPlugin
  
